import type { AnimeResponse, GenreResponse } from "./api";

// Simplified fallback data for when API rate limit is reached
export const popularAnimeFallback: AnimeResponse = {
  data: [
    {
      id: 1,
      title: "One Piece",
      title_english: "One Piece",
      title_japanese: "ワンピース",
      image: "https://cdn.myanimelist.net/images/anime/6/73245.jpg",
      images: {
        jpg: {
          image_url: "https://cdn.myanimelist.net/images/anime/6/73245.jpg",
        },
      },
      trailer: {
        youtube_id: "l_98K4_6UQ0",
        url: "https://www.youtube.com/watch?v=l_98K4_6UQ0",
        embed_url: "https://www.youtube.com/embed/l_98K4_6UQ0",
      },
      type: "TV",
      source: "Manga",
      episodes: 0,
      status: "Currently Airing",
      airing: true,
      aired: {
        from: "1999-10-20T00:00:00+00:00",
        to: "", // Changed from null to empty string
        string: "Oct 20, 1999 to ?",
      },
      duration: "24 min",
      rating: "PG-13",
      score: 8.69,
      rank: 44,
      popularity: 12,
      synopsis: "Gol D. Roger was known as the Pirate King...",
      genres: [
        { id: 1, name: "Action" },
        { id: 2, name: "Adventure" },
      ],
      year: 1999,
      studios: [{ id: 18, name: "Toei Animation" }],
    },
    {
      id: 2,
      title: "Attack on Titan",
      title_english: "Attack on Titan",
      title_japanese: "進撃の巨人",
      image: "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
      images: {
        jpg: {
          image_url: "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
        },
      },
      trailer: {
        youtube_id: "LHtdKWJdif4",
        url: "https://www.youtube.com/watch?v=LHtdKWJdif4",
        embed_url: "https://www.youtube.com/embed/LHtdKWJdif4",
      },
      type: "TV",
      source: "Manga",
      episodes: 25,
      status: "Finished Airing",
      airing: false,
      aired: {
        from: "2013-04-07T00:00:00+00:00",
        to: "2013-09-29T00:00:00+00:00",
        string: "Apr 7, 2013 to Sep 29, 2013",
      },
      duration: "24 min per ep",
      rating: "R - 17+ (violence & profanity)",
      score: 8.53,
      rank: 89,
      popularity: 2,
      synopsis: "Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures...",
      genres: [
        { id: 1, name: "Action" },
        { id: 8, name: "Drama" },
      ],
      year: 2013,
      studios: [{ id: 858, name: "Wit Studio" }],
    },
  ],
  pagination: {
    last_visible_page: 1,
    has_next_page: false,
    current_page: 1,
    items: {
      count: 2,
      total: 2,
      per_page: 25,
    },
  },
};

export const recentAnimeFallback = { ...popularAnimeFallback };

export const genresFallback: GenreResponse = {
  data: [
    { id: 1, name: "Action", count: 4558 },
    { id: 2, name: "Adventure", count: 3824 },
    { id: 3, name: "Cars", count: 253 },
    { id: 4, name: "Comedy", count: 7083 },
    { id: 5, name: "Dementia", count: 0 },
    { id: 6, name: "Demons", count: 537 },
    { id: 7, name: "Mystery", count: 895 },
    { id: 8, name: "Drama", count: 2667 },
    { id: 9, name: "Ecchi", count: 739 },
    { id: 10, name: "Fantasy", count: 3975 },
    { id: 11, name: "Game", count: 187 },
    { id: 12, name: "Hentai", count: 0 },
    { id: 13, name: "Historical", count: 1433 },
    { id: 14, name: "Horror", count: 509 },
    { id: 15, name: "Kids", count: 5921 },
    { id: 16, name: "Magic", count: 0 },
    { id: 17, name: "Martial Arts", count: 539 },
    { id: 18, name: "Mecha", count: 1237 },
    { id: 19, name: "Music", count: 3097 },
    { id: 20, name: "Parody", count: 0 },
    { id: 21, name: "Samurai", count: 212 },
    { id: 22, name: "Romance", count: 1883 },
    { id: 23, name: "School", count: 1943 },
    { id: 24, name: "Sci-Fi", count: 2857 },
    { id: 25, name: "Shoujo", count: 0 },
    { id: 26, name: "Shoujo Ai", count: 0 },
    { id: 27, name: "Shounen", count: 0 },
    { id: 28, name: "Shounen Ai", count: 0 },
    { id: 29, name: "Space", count: 565 },
    { id: 30, name: "Sports", count: 705 },
    { id: 31, name: "Super Power", count: 0 },
    { id: 32, name: "Vampire", count: 149 },
    { id: 33, name: "Yaoi", count: 0 },
    { id: 34, name: "Yuri", count: 0 },
    { id: 35, name: "Harem", count: 0 },
    { id: 36, name: "Slice of Life", count: 1486 },
    { id: 37, name: "Supernatural", count: 1440 },
    { id: 38, name: "Military", count: 0 },
    { id: 39, name: "Police", count: 0 },
    { id: 40, name: "Psychological", count: 387 },
    { id: 41, name: "Thriller", count: 0 },
    { id: 42, name: "Seinen", count: 0 },
    { id: 43, name: "Josei", count: 0 },
  ],
};
