[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*", "https://*.apiclub.site/*", "https://cdn.myanimelist.net/*"]

[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_STATIC_EXPORT = "true"
